// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF7OMHllmJMStMCapcdhlIpIhjjcV8zRc',
    appId: '1:981315297520:web:84e13e880d2546d5846235',
    messagingSenderId: '981315297520',
    projectId: 'flutter-remidi-pab',
    authDomain: 'flutter-remidi-pab.firebaseapp.com',
    storageBucket: 'flutter-remidi-pab.firebasestorage.app',
    measurementId: 'G-QY2SBR334V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xtC9rM0d3DnXLZ2F8d1_q8tO8xwWXiQ',
    appId: '1:981315297520:android:294e74288de7bcfb846235',
    messagingSenderId: '981315297520',
    projectId: 'flutter-remidi-pab',
    storageBucket: 'flutter-remidi-pab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJ_dnyiz8QFbHL8XmEsf-5M7Wwx_J1bA',
    appId: '1:981315297520:ios:a1241b8e3a642398846235',
    messagingSenderId: '981315297520',
    projectId: 'flutter-remidi-pab',
    storageBucket: 'flutter-remidi-pab.firebasestorage.app',
    iosBundleId: 'com.example.flutterRemidiPab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFJ_dnyiz8QFbHL8XmEsf-5M7Wwx_J1bA',
    appId: '1:981315297520:ios:a1241b8e3a642398846235',
    messagingSenderId: '981315297520',
    projectId: 'flutter-remidi-pab',
    storageBucket: 'flutter-remidi-pab.firebasestorage.app',
    iosBundleId: 'com.example.flutterRemidiPab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF7OMHllmJMStMCapcdhlIpIhjjcV8zRc',
    appId: '1:981315297520:web:04fcf0af76123d02846235',
    messagingSenderId: '981315297520',
    projectId: 'flutter-remidi-pab',
    authDomain: 'flutter-remidi-pab.firebaseapp.com',
    storageBucket: 'flutter-remidi-pab.firebasestorage.app',
    measurementId: 'G-CD07KG66HY',
  );
}
